export const accountsConfig = [
  { value: "none", label: "None" },
  { value: "analyst", label: "Analyst" },
  { value: "competitor", label: "Competitor" },
  { value: "customer", label: "Customer" },
  { value: "distributor", label: "Distributor" },
  { value: "integrator", label: "Integrator" },
  { value: "investor", label: "Investor" },
  { value: "other", label: "Other" },
  { value: "partner", label: "Partner" },
  { value: "press", label: "Press" },
  { value: "prospect", label: "Prospect" },
  { value: "reseller", label: "Reseller" },
  { value: "supplier", label: "Supplier" },
  { value: "vendor", label: "Vendor" },
];
export const industriesConfig = [
  { value: "none", label: "None" },
  { value: "asp", label: "ASP(Application Service Provider)" },
  { value: "telecom", label: "Data/Telecom OEM" },
  { value: "erp", label: "ERP (Enterprise Resource Planning)" },
  { value: "government", label: "Government/Military" },
  { value: "largeEnterprise", label: "Large Enterprise" },
  { value: "managementISV", label: "Management ISV" },
  { value: "msp", label: "MSP (Management Service Provider)" },
  { value: "nee", label: "Network Equipment Enterprise" },
  { value: "nonManagementISV", label: "Non-Management ISV" },
  { value: "opticalNetworking", label: "Optical Networking" },
  { value: "serviceProvider", label: "Service Provider" },
  { value: "medium/Enterprise", label: "Small/Medium Enterprise" },
  { value: "storageEquipment", label: "Storage Equipment" },
  { value: "storageServiceProvider", label: "Storage Service Provider" },
  { value: "systemIntegrator", label: "System Integrator" },
  { value: "wirelessIndustry", label: "Wireless Industry" },
  { value: "financialServices", label: "Financial Services" },
  { value: "education", label: "Education" },
  { value: "technology", label: "Technology" },
  { value: "realEstate", label: "Real Estate" },
  { value: "consulting", label: "Consulting" },
  { value: "communications", label: "Communications" },
  { value: "maufacturing", label: "Manufacturing" },
];
