export const frameworksConfig = [
  { value: "none", label: "None" },
  { value: "advertisement", label: "Advertisement" },
  { value: "employeeReferral", label: "Employee Referral" },
  { value: "externalReferral", label: "External Referral" },
  { value: "onlineStore", label: "Online Store" },
  { value: "twitter", label: "X (Twitter)" },
  { value: "facebook", label: "X (Facebook)" },
  { value: "partner", label: "Partner" },
  { value: "publicRelations", label: "Public Relations" },
  { value: "salesEmailAlias", label: "Sales Email Alias" },
  { value: "seminarPartner", label: "Seminar Partner" },
  { value: "internalSeminar", label: "Internal Seminar" },
  { value: "tradeShow", label: "Trade Show" },
  { value: "webDownload", label: "Web Download" },
  { value: "webResearch", label: "Web Research" },
  { value: "chat", label: "Chat" },
];
export const industriesConfig = [
  { value: "none", label: "None" },
  { value: "asp", label: "ASP(Application Service Provider)" },
  { value: "telecom", label: "Data/Telecom OEM" },
  { value: "erp", label: "ERP (Enterprise Resource Planning)" },
  { value: "government", label: "Government/Military" },
  { value: "largeEnterprise", label: "Large Enterprise" },
  { value: "managementISV", label: "Management ISV" },
  { value: "msp", label: "MSP (Management Service Provider)" },
  { value: "nee", label: "Network Equipment Enterprise" },
  { value: "nonManagementISV", label: "Non-Management ISV" },
  { value: "opticalNetworking", label: "Optical Networking" },
  { value: "serviceProvider", label: "Service Provider" },
  { value: "medium/Enterprise", label: "Small/Medium Enterprise" },
  { value: "storageEquipment", label: "Storage Equipment" },
  { value: "storageServiceProvider", label: "Storage Service Provider" },
  { value: "systemIntegrator", label: "System Integrator" },
  { value: "wirelessIndustry", label: "Wireless Industry" },
  { value: "erp", label: "ERP" },
];
